[sncast.alpha-sepolia]
account = "emman"
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"

[sncast.alpha-mainnet]
account = "emman"  
url = "https://starknet-mainnet.public.blastapi.io/rpc/v0_7"